"""
Project directory setup utilities.

Called by the orchestrator to:
1. Bootstrap a competition project directory with Claude Code native config
   (.claude/agents/, .claude/skills/, .claude/settings.json, hook scripts).
2. Write/refresh CLAUDE.md — the shared context document loaded automatically
   by all agents (Claude Code loads it from the working directory at session
   start; agents also receive it as part of their context).

All writes are idempotent for bootstrap files (skip if already exist), but
CLAUDE.md is always overwritten because it carries live competition state.
"""

from __future__ import annotations

import json
import os
import stat
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from gladius.state import CompetitionState

# ── CLAUDE.md ─────────────────────────────────────────────────────────────────


def write_claude_md(state: "CompetitionState", project_dir: str) -> None:
    """
    Overwrite CLAUDE.md in project_dir with the current competition state.

    This is called at the start of every iteration so every agent sees
    fresh context without needing it injected into every prompt.
    """
    p = Path(project_dir) / "CLAUDE.md"

    best_oof = (
        f"{state.best_oof_score:.6f}" if state.best_oof_score >= 0 else "none yet"
    )
    best_lb = (
        f"{state.best_submission_score:.6f}"
        if state.best_submission_score >= 0
        else "none yet"
    )
    direction_str = (
        "↑ higher is better"
        if state.metric_direction == "maximize"
        else "↓ lower is better"
    )

    # Top-5 experiments, newest first
    exps = list(reversed(state.experiments[-5:]))
    exp_lines = "_(none yet)_"
    if exps:
        rows = []
        for e in exps:
            s = e.get("oof_score", "?")
            n = e.get("notes", "")[:100]
            it = e.get("iteration", "?")
            files = ", ".join(Path(f).name for f in e.get("solution_files", []))
            rows.append(f"| iter {it} | {s} | {files} | {n} |")
        exp_lines = (
            "| Iteration | OOF Score | Files | Notes |\n| --- | --- | --- | --- |\n"
        ) + "\n".join(rows)

    # Failed approaches to avoid
    failed_lines = "_(none)_"
    if state.failed_runs:
        failed_lines = "\n".join(
            f"- iter {f.get('iteration', '?')}: {f.get('error', '?')[:80]}"
            for f in state.failed_runs[-5:]
        )

    # Stagnation detection — warn planner if last 3 experiments barely moved
    stagnation_block = ""
    scored = [e for e in state.experiments if e.get("oof_score") is not None]
    if len(scored) >= 3:
        last3 = [e["oof_score"] for e in scored[-3:]]
        span = max(last3) - min(last3)
        stagnation_threshold = 0.001
        if span < stagnation_threshold:
            stagnation_block = f"""
## ⚠️ STAGNATION WARNING

> The last **{len(last3)} experiments** moved the {state.target_metric} score by only
> **{span:.6f}** (threshold: {stagnation_threshold}). Incremental tweaks are not working.
>
> **Planner: stop tuning. Go back to first principles.**
> - Re-examine raw data (distributions, leakage, target encoding issues).
> - Try a completely different model family or feature representation.
> - Consider if the metric is being computed correctly.
> - WebSearch for breakthrough techniques specific to this competition type.
"""

    content = f"""\
# Competition: {state.competition_id}

> **This file is auto-generated by Gladius and refreshed every iteration.**
> Read it first before doing anything else.

## Competition Settings

| Field | Value |
| --- | --- |
| Competition ID | `{state.competition_id}` |
| Target metric | `{state.target_metric}` ({direction_str}) |
| Data directory | `{state.data_dir}` |
| Output directory | `{state.output_dir}` |
| Iteration | {state.iteration} / {state.max_iterations} |
| Phase | {state.phase} |

## Current Best

| Metric | Score |
| --- | --- |
| Best OOF ({state.target_metric}) | **{best_oof}** |
| Best leaderboard | **{best_lb}** |
| Submissions today | {state.submission_count} / {state.max_submissions_per_day} |

## Recent Experiments

{exp_lines}

## Failed Approaches (avoid repeating)

{failed_lines}
{stagnation_block}
## Data Files

```bash
ls {state.data_dir}
```

Standard files to expect:
- `train.csv` — training set (target column present)
- `test.csv` — test set (no target column)
- `sample_submission.csv` — submission format template

## Submission Rules

1. Load `sample_submission.csv` to get the exact submission format.
2. Your submission must match its columns and row count exactly.
3. Save as a CSV in the project directory.
4. Report the path in `submission_file` in your output.

## Agent Memory

If you are the **planner**, read your agent memory at
`.claude/agent-memory/planner/MEMORY.md` before exploring.
Update it with insights after each exploration session.

If you are an **implementer**, focus only on executing the given plan.

## Package Management

> **This project uses `uv` — there is no `pip` in the venv.**
> **Always install packages with:** `uv add <package>`
> Never use `pip install`, `pip3 install`, or `python -m pip install`.

```bash
uv add optuna catboost lightgbm   # install packages
uv run python solution.py         # run a script inside the venv
```
"""
    p.write_text(content, encoding="utf-8")


# ── Bootstrap project .claude/ structure ──────────────────────────────────────


def setup_project_dir(state: "CompetitionState", project_dir: str) -> None:
    """
    One-time (idempotent) setup of Claude Code native config in project_dir.

    Creates:
    - .claude/agents/planner.md
    - .claude/agents/implementer.md
    - .claude/skills/ml-pipeline/SKILL.md
    - .claude/skills/submit-check/SKILL.md
    - .claude/settings.json  (hooks + env)
    - .mcp.json              (MCP server registrations for CLI use)
    - scripts/after_edit.sh  (PostToolUse hook: compile Python on edit)
    - scripts/validate_bash.sh (PreToolUse hook: block dangerous rm -rf)
    """
    root = Path(project_dir)

    _write_agent_planner(root)
    _write_agent_implementer(root)
    _write_skill_ml_pipeline(root)
    _write_skill_submit_check(root)
    _write_skill_git_workflow(root)
    _write_skill_uv_venv(root)
    _write_skill_code_review(root)
    _write_claude_settings(root, state)
    _write_mcp_json(root, state)
    _write_hook_after_edit(root)
    _write_hook_validate_bash(root)
    _make_memory_dir(root)


# ── Agent definitions ─────────────────────────────────────────────────────────


def _write_agent_planner(root: Path) -> None:
    # Always overwrite so that permission mode and content stay in sync.
    path = root / ".claude" / "agents" / "planner.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""\
---
name: planner
description: >
  Expert ML competition analyst. Explores data, reviews experiment history,
  and decides the highest-impact next approach. Use proactively at the start
  of each competition iteration.
tools: Read, Glob, Grep, Bash, WebSearch, Task
model: {os.environ.get('GLADIUS_MODEL', 'GLADIUS_MODEL_NOT_SET')}
memory: project
maxTurns: 40
permissionMode: bypassPermissions
---

You are an expert ML competition analyst.

**Start every session by:**
1. Reading `CLAUDE.md` in the current directory for competition state.
2. Reading your agent memory at `.claude/agent-memory/planner/MEMORY.md`.
3. Exploring the data directory and any existing solution files.

**Your job:**
- Understand what has already been tried (from CLAUDE.md experiments table).
- Identify the highest-impact next approach (new features, different model,
  hyperparameter tuning, stacking, etc.).
- Produce a concrete, ordered action plan the implementer can execute blindly.

**Rules:**
- You NEVER write implementation code yourself. You plan; implementer executes.
- Plans must be specific and self-contained — no "investigate X" steps.
- Update your memory with key insights (data quirks, what worked, what didn't).
- WebSearch for competition-specific techniques when you lack domain knowledge.
""",
        encoding="utf-8",
    )


def _write_agent_implementer(root: Path) -> None:
    # Always overwrite so that permission mode and content stay in sync.
    path = root / ".claude" / "agents" / "implementer.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""\
---
name: implementer
description: >
  Expert ML engineer. Executes the planner's plan end-to-end: writes code,
  runs it, debugs errors, measures the metric, and reports results.
  Always gets a fresh context — does not retain knowledge between runs.
tools: Read, Write, Edit, Bash, Glob, Grep
model: {os.environ.get('GLADIUS_MODEL', 'GLADIUS_MODEL_NOT_SET')}
maxTurns: 80
permissionMode: bypassPermissions
---

You are an expert ML engineer executing a competition experiment.

**Start every session by:**
1. Reading `CLAUDE.md` in the current directory for competition context.
2. Reading the plan provided to you in the task description.

**Your job:**
- Implement the plan completely.
- Run the code, fix any errors you encounter, repeat until it works.
- Measure the target metric using OOF / cross-validation.
- Produce a `submission.csv` (or similarly named file) for the test set.
- Report the final metric score and all file paths you created.

**Rules:**
- You decide file names, libraries, and code structure. No constraints.
- Never hard-code the metric — compute it programmatically.
- Always validate submission shape against `sample_submission.csv`.
- Keep all created files; never delete previous solutions.

**When you're done, before reporting results:**
- Invoke the `code-review` skill (read `.claude/skills/code-review/SKILL.md`) and
  fix every CRITICAL item before finalising.

**Report:**
- `status`: success | error | timeout | oom
- `oof_score`: the OOF metric value you measured (-1 on failure)
- `solution_files`: list of all files you created or modified
- `submission_file`: path to the test-set predictions CSV
- `notes`: brief summary of what you built and the score
- `error_message`: (only on failure) what went wrong
""",
        encoding="utf-8",
    )


# ── Skills ────────────────────────────────────────────────────────────────────


def _write_skill_ml_pipeline(root: Path) -> None:
    path = root / ".claude" / "skills" / "ml-pipeline" / "SKILL.md"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
---
name: ml-pipeline
description: >
  ML competition pipeline best practices. Auto-loaded when writing or
  debugging competition ML code.
user-invocable: false
---

## Validation

- **Classification**: StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
- **Regression**: KFold(n_splits=5, shuffle=True, random_state=42)
- Fit on train folds, predict on validation fold, aggregate OOF predictions.
- Compute the competition metric on the full OOF array (not fold averages).

## Baselines

- Tabular: **LightGBM** or **XGBoost** first (fast, strong default).
- Deep learning: only after a solid gradient boosting baseline exists.
- Always record baseline score before any feature engineering.

## Feature Engineering

- Log every engineered feature in a comment explaining the hypothesis.
- Never fit target-based encodings on the full training set — always compute
  within each CV fold to avoid leakage.
- Drop ID columns and date columns (unless engineering lag features).

## Metrics

| Competition type | Metric | sklearn call |
| --- | --- | --- |
| Binary classification | AUC-ROC | `roc_auc_score(y_true, y_score)` |
| Multiclass | Log loss | `log_loss(y_true, y_proba)` |
| Regression | RMSE | `mean_squared_error(y_true, y_pred, squared=False)` |

Always `print(f"OOF {metric_name}: {score:.6f}")` so the score appears in logs.

## Submission Format

```python
import pandas as pd
sample_sub = pd.read_csv("data/sample_submission.csv")  # or data_dir
sub = sample_sub.copy()
sub[sub.columns[-1]] = test_predictions  # fill prediction column
assert len(sub) == len(sample_sub), "Row count mismatch!"
assert not sub.isnull().any().any(), "NaN in submission!"
sub.to_csv("submission.csv", index=False)
print(f"Submission saved: {len(sub)} rows, columns: {list(sub.columns)}")
```

## File Naming

- Name solution scripts descriptively: `solution_lgbm_baseline.py`, `solution_xgb_v2.py`
- Keep ALL previous solution files — never delete older versions.
- Write a `run.sh` if the solution has multiple steps.
""",
        encoding="utf-8",
    )


def _write_skill_submit_check(root: Path) -> None:
    path = root / ".claude" / "skills" / "submit-check" / "SKILL.md"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
---
name: submit-check
description: Validate a submission CSV before platform upload
disable-model-invocation: true
allowed-tools: Bash, Read
---

Validate the submission file at $ARGUMENTS against the sample submission.

Steps:
1. Load `data/sample_submission.csv` (or find sample_submission.csv in the data dir)
2. Load the submission at `$ARGUMENTS`
3. Check that column names match exactly (same order and names)
4. Check that row counts match
5. Check for NaN or Inf in all numeric columns
6. For probability predictions: check all values are in [0, 1]
7. For regression: check values are in a sane range (warn if extreme outliers)

Output:
- `VALID` if all checks pass
- `INVALID: <reason>` listing specific issues
""",
        encoding="utf-8",
    )


def _write_skill_code_review(root: Path) -> None:
    path = root / ".claude" / "skills" / "code-review" / "SKILL.md"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
---
name: code-review
description: Review ML solution code before finalising — catch leakage, metric errors, and format bugs
allowed-tools: Read, Bash
---

Before finalising any solution script, review it against this checklist.
Fix every item marked CRITICAL before reporting results.

## CRITICAL — data leakage

- [ ] Target-based encodings (mean encoding, target encoding) are computed
      **inside** each CV fold, never on the full training set.
- [ ] Temporal features (lag, rolling stats) use only past data — no future leakage.
- [ ] No test-set rows accidentally appear in the training fold.
- [ ] StandardScaler / other transformers are fit on train fold only, then applied to val/test.
- [ ] `train_test_split` is NOT used instead of proper k-fold CV.

## CRITICAL — metric correctness

- [ ] The OOF metric is computed on out-of-fold predictions, not train predictions.
- [ ] The metric function matches the competition definition exactly
      (e.g. `average='macro'` vs `average='binary'` for F1).
- [ ] For probability metrics (AUC, log-loss): predictions are probabilities, not class labels.
- [ ] The metric direction (maximize/minimize) is respected when comparing scores.

## CRITICAL — submission format

- [ ] Submission CSV column names match `sample_submission.csv` exactly.
- [ ] Submission row count matches `sample_submission.csv` exactly.
- [ ] No NaN or Inf in prediction column.
- [ ] File is saved to the path reported in `submission_file`.

## Important — robustness

- [ ] No hard-coded file paths — use variables from CLAUDE.md context.
- [ ] Random seeds set for reproducibility (`random_state=42`, `np.random.seed(42)`).
- [ ] OOF score is printed as `OOF {metric}: {score:.6f}` so it appears in logs.
- [ ] Script runs end-to-end without manual intervention.

## Style

- [ ] Each feature engineering step has a comment explaining the hypothesis.
- [ ] File name is descriptive: `solution_lgbm_v2.py`, not `solution.py`.
""",
        encoding="utf-8",
    )


def _write_skill_git_workflow(root: Path) -> None:
    path = root / ".claude" / "skills" / "git-workflow" / "SKILL.md"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
---
name: git-workflow
description: Commit every working solution version with a descriptive message
allowed-tools: Bash
---

After implementing a solution that runs without errors and produces an OOF score,
stage and commit it locally:

```bash
git add -A
git commit -m "iter-{N}: {approach_summary} — OOF {score:.6f}"
```

Guidelines:
- Commit only after the solution script runs end-to-end without errors.
- Use `git add -A` to stage everything (solution file, submission CSV, run.sh).
- Message format: `iter-{N}: <one-sentence approach> — OOF {metric}={score:.6f}`
- Never force-push. Never rebase during a competition run.
- If a run fails, do NOT commit. Just proceed to the next iteration.
- Check `git status` before committing to avoid committing unintended files.
- `.gladius/` and `data/` should already be in `.gitignore` — verify if unsure.

Tip: use `git log --oneline -10` to review recent iteration history.
""",
        encoding="utf-8",
    )


def _write_skill_uv_venv(root: Path) -> None:
    path = root / ".claude" / "skills" / "uv-venv" / "SKILL.md"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
---
name: uv-venv
description: Install Python packages and run scripts using uv
allowed-tools: Bash
---

This project uses **uv** for fast Python package management.
Never use `pip install` directly — always use `uv add` or `uv run`.

## Installing packages

```bash
# Add a runtime dependency (updates pyproject.toml + uv.lock)
uv add lightgbm scikit-learn pandas numpy

# Add a dev/optional dependency
uv add --dev pytest

# Sync the environment (install all locked deps)
uv sync
```

## Running scripts

```bash
# Run a script inside the venv without activating it
uv run python solution_lgbm.py

# Run with extra args
uv run python solution_lgbm.py --folds 5 --seed 42

# Run a one-liner
uv run python -c "import lightgbm; print(lightgbm.__version__)"
```

## Checking installed packages

```bash
uv pip list
uv pip show lightgbm
```

## Notes
- `uv` is already installed. The venv is in `.venv/`.
- Prefer `uv add` over editing `pyproject.toml` manually.
- `uv.lock` should be committed to git for reproducibility.
- If a package needs a non-PyPI source (e.g. GPU build), use
  `uv add --index https://... package_name`.
""",
        encoding="utf-8",
    )


# ── .claude/settings.json ─────────────────────────────────────────────────────


def _write_claude_settings(root: Path, state: "CompetitionState") -> None:
    path = root / ".claude" / "settings.json"
    # Always overwrite to keep env vars (competition ID etc.) up to date.
    path.parent.mkdir(parents=True, exist_ok=True)
    settings = {
        "model": os.environ.get("GLADIUS_MODEL") or "GLADIUS_MODEL_NOT_SET",
        "env": {
            "COMPETITION_ID": state.competition_id,
            "TARGET_METRIC": state.target_metric,
            "METRIC_DIRECTION": state.metric_direction,
            "DATA_DIR": state.data_dir,
        },
        "hooks": {
            "PostToolUse": [
                {
                    "matcher": "Edit|Write",
                    "hooks": [{"type": "command", "command": "scripts/after_edit.sh"}],
                }
            ],
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {"type": "command", "command": "scripts/validate_bash.sh"}
                    ],
                }
            ],
        },
    }
    path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")


# ── .mcp.json (for Claude Code CLI use) ──────────────────────────────────────


def _write_mcp_json(root: Path, state: "CompetitionState") -> None:
    path = root / ".mcp.json"
    if path.exists():
        return
    import sys

    mcp_config: dict = {
        "mcpServers": {
            "metric-tools": {
                "type": "stdio",
                "command": sys.executable,
                "args": [
                    "-c",
                    (
                        "from gladius.tools.metric_tools import server; "
                        "import asyncio; asyncio.run(server.run())"
                    ),
                ],
                "env": {},
            }
        }
    }
    path.write_text(json.dumps(mcp_config, indent=2) + "\n", encoding="utf-8")


# ── Hook scripts ──────────────────────────────────────────────────────────────


def _write_hook_after_edit(root: Path) -> None:
    path = root / "scripts" / "after_edit.sh"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
#!/usr/bin/env bash
# PostToolUse hook — runs after Edit or Write tool calls.
# Compiles any modified Python file immediately so Claude sees syntax errors
# in the same turn rather than discovering them at runtime.
#
# Exit code 2 = send error back to Claude and block (Claude will fix it).
# Exit code 0 = success, continue normally.

INPUT=$(cat)

# Extract file path from tool_input (Edit sets 'path', Write sets 'path')
FILE_PATH=$(python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    ti = d.get('tool_input', {})
    print(ti.get('file_path', ''))  # SDK Write and Edit both use 'file_path'
except Exception:
    print('')
" <<< "$INPUT" 2>/dev/null || echo "")

if [[ "$FILE_PATH" == *.py ]] && [[ -f "$FILE_PATH" ]]; then
    ERRORS=$(python3 -m py_compile "$FILE_PATH" 2>&1)
    if [[ -n "$ERRORS" ]]; then
        echo "Syntax error detected in $FILE_PATH — fix before continuing:" >&2
        echo "$ERRORS" >&2
        exit 2
    fi
fi

exit 0
""",
        encoding="utf-8",
    )
    _make_executable(path)


def _write_hook_validate_bash(root: Path) -> None:
    path = root / "scripts" / "validate_bash.sh"
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """\
#!/usr/bin/env bash
# PreToolUse hook — runs before every Bash tool call.
# Blocks commands that could destroy data outside the project directory.
#
# Exit code 2 = block the command and send the error message to Claude.
# Exit code 0 = allow the command.

INPUT=$(cat)

COMMAND=$(python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('tool_input', {}).get('command', ''))
except Exception:
    print('')
" <<< "$INPUT" 2>/dev/null || echo "")

# Block recursive delete of absolute paths (outside project)
if echo "$COMMAND" | grep -qE 'rm[[:space:]]+-[a-zA-Z]*r[a-zA-Z]*f[[:space:]]+/'; then
    echo "Blocked: 'rm -rf /' style command is not allowed. Use relative paths only." >&2
    exit 2
fi

# Block recursive delete of home directory
if echo "$COMMAND" | grep -qE 'rm[[:space:]]+-[a-zA-Z]*r[a-zA-Z]*f[[:space:]]+~'; then
    echo "Blocked: 'rm -rf ~' is not allowed." >&2
    exit 2
fi

exit 0
""",
        encoding="utf-8",
    )
    _make_executable(path)


# ── Agent memory directory ────────────────────────────────────────────────────


def _make_memory_dir(root: Path) -> None:
    """Pre-create the planner's memory directory so it exists on first run."""
    mem_dir = root / ".claude" / "agent-memory" / "planner"
    mem_dir.mkdir(parents=True, exist_ok=True)
    mem_file = mem_dir / "MEMORY.md"
    if not mem_file.exists():
        mem_file.write_text(
            """\
# Planner Memory

> Auto-updated by summarizer. Last iteration: 0

## Key Data Insights

_(Add notes here as you explore the dataset)_

## What Works  ✅

_(Record successful approaches with approximate OOF delta and iteration number)_

## What Fails / Dead Ends  ❌

_(Record approaches that hurt score, timed out, or errored — include the reason)_

## Patterns & Hypotheses  💡

_(Open hypotheses not yet tested, or correlations observed in data)_

## Experiment Score History

| iter | OOF | approach | notes |
| --- | --- | --- | --- |

## Suggested Next Directions

1. Establish a baseline (LightGBM or XGBoost) before any feature engineering.
""",
            encoding="utf-8",
        )


# ── Utility ───────────────────────────────────────────────────────────────────


def _make_executable(path: Path) -> None:
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
